#ifndef PROJECT_NAME_RESIDS_HPP
#define PROJECT_NAME_RESIDS_HPP


// !max value is type short max (32767)
#define PROJECT_NAME_ABOUT_STRINGSID	32000
#define PROJECT_NAME_MENU_STRINGSID		32500

#endif // PROJECT_NAME_RESIDS_HPP